# Generated by Django 4.0 on 2021-12-27 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetmasterapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='pension_non_risk_asset_flag',
            field=models.BooleanField(default=False),
        ),
    ]
