# Generated by Django 4.0 on 2022-01-13 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetmasterapp', '0002_asset_pension_non_risk_asset_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('EQUITY', 'Equity'), ('GUARDIAN', 'Guardian'), ('REITS', 'Reits'), ('PENSION', 'Pension'), ('CRYPTO', 'Crypto Asset')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='market',
            field=models.CharField(choices=[('KSE', 'Korean Stock Exchange(KSE)'), ('NASDAQ', 'NASDAQ'), ('NYSE', 'NewYork Stock Exchange(NYSE)'), ('NA', 'Not Applicable')], max_length=100, null=True),
        ),
    ]
