# Generated by Django 4.0 on 2022-01-13 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetmasterapp', '0003_alter_asset_asset_type_alter_asset_market'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='image',
            field=models.ImageField(default='static/images/diamond_goose_logo_mk1.png', upload_to='assetmaster/'),
        ),
    ]
