# Generated by Django 4.0 on 2022-01-10 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equityapp', '0002_equitytransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='equity',
            name='total_dividend_amount',
            field=models.FloatField(default=0),
        ),
    ]
