# Generated by Django 4.0 on 2022-01-15 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equityapp', '0003_equity_total_dividend_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equitytransaction',
            name='split_cnt',
        ),
        migrations.AddField(
            model_name='equitytransaction',
            name='split_ratio_one_to_N',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
