# Generated by Django 4.0 on 2022-01-15 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reitsapp', '0002_reitstransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reitstransaction',
            name='split_cnt',
        ),
        migrations.AddField(
            model_name='reitstransaction',
            name='split_ratio_one_to_N',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
