# Generated by Django 4.0 on 2022-01-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reitsapp', '0003_remove_reitstransaction_split_cnt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reits',
            name='total_dividend_amount',
            field=models.FloatField(default=0),
        ),
    ]
