# Generated by Django 4.0 on 2022-01-08 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('exchangeapp', '0002_myexchange_dashboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForeignCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_exchange_rate', models.FloatField(default=0)),
                ('current_amount', models.FloatField(default=0)),
                ('accumulated_exchange_rate_mv', models.FloatField(default=0)),
                ('accumulated_exchange_rate_fifo', models.FloatField(default=0)),
                ('exchange_rate_of_return_mv', models.FloatField(default=0)),
                ('exchange_rate_of_return_fifo', models.FloatField(default=0)),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foreign_currency', to='exchangeapp.myexchange')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foreign_currency', to='auth.user')),
            ],
        ),
    ]
