# Generated by Django 4.0 on 2022-01-08 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchangeapp', '0003_foreigncurrency'),
    ]

    operations = [
        migrations.AddField(
            model_name='foreigncurrency',
            name='currency',
            field=models.CharField(choices=[('KRW', 'Korean Won(￦)'), ('USD', 'US Dollar($)')], default='USD', max_length=10),
            preserve_default=False,
        ),
    ]
