# Generated by Django 4.0 on 2022-01-10 02:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import exchangeapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('exchangeapp', '0004_foreigncurrency_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForeignCurrencyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('BUY', '매수'), ('SELL', '매도')], max_length=20)),
                ('quantity', exchangeapp.models.MinValueFloat()),
                ('exchange_rate', exchangeapp.models.MinValueFloat(default=0)),
                ('transaction_fee', models.FloatField(default=0)),
                ('transaction_tax', models.FloatField(default=0)),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.CharField(default=' - ', max_length=40, null=True)),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('last_update_date', models.DateTimeField(auto_now_add=True)),
                ('foreign_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='exchangeapp.foreigncurrency')),
            ],
        ),
    ]
