# Generated by Django 4.0 on 2022-01-10 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchangeapp', '0005_foreigncurrencytransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foreigncurrencytransaction',
            name='transaction_fee',
        ),
        migrations.RemoveField(
            model_name='foreigncurrencytransaction',
            name='transaction_tax',
        ),
    ]
