# Generated by Django 4.0 on 2022-01-12 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchangeapp', '0006_remove_foreigncurrencytransaction_transaction_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foreigncurrency',
            name='currency',
            field=models.CharField(choices=[('KRW', 'Korean Won(￦)'), ('USD', 'US Dollar($)'), ('JPY', 'Japanese Yen(¥)')], max_length=10),
        ),
        migrations.AlterField(
            model_name='myexchange',
            name='main_currency',
            field=models.CharField(choices=[('KRW', 'Korean Won(￦)'), ('USD', 'US Dollar($)'), ('JPY', 'Japanese Yen(¥)')], max_length=10),
        ),
    ]
