# Generated by Django 4.0 on 2021-12-23 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assetmasterapp', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('dashboardapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pension_type', models.CharField(choices=[('퇴직연금', '퇴직연금'), ('연금저축', '연금저축'), ('IRP', 'IRP')], max_length=30)),
                ('total_paid_amount', models.FloatField(default=0)),
                ('total_current_value', models.FloatField(default=0)),
                ('total_profit_amount', models.FloatField(default=0)),
                ('rate_of_return', models.FloatField(default=0)),
                ('risk_ratio_force_flag', models.BooleanField(default=False)),
                ('risk_ratio', models.FloatField(default=0.7, null=True)),
                ('current_risk_asset_ratio', models.FloatField(default=0, null=True)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pension', to='dashboardapp.dashboard')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pension', to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='PensionTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('PAY', '납입'), ('RECEIVE', '수령')], max_length=20)),
                ('amount', models.FloatField(default=0)),
                ('transaction_date', models.DateTimeField()),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('last_update_date', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pension_transaction', to='auth.user')),
                ('pension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pension_transaction', to='pensionapp.pension')),
            ],
        ),
        migrations.CreateModel(
            name='PensionAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0)),
                ('total_amount', models.FloatField(default=0)),
                ('average_purchase_price_mv', models.FloatField(default=0)),
                ('average_purchase_price_fifo', models.FloatField(default=0)),
                ('rate_of_return_mv', models.FloatField(default=0)),
                ('rate_of_return_fifo', models.FloatField(default=0)),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('last_update_date', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pension_asset', to='assetmasterapp.asset')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pension_asset', to='auth.user')),
                ('pension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pension_asset', to='pensionapp.pension')),
            ],
        ),
    ]
