# Generated by Django 4.0 on 2021-12-24 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pensionapp', '0002_remove_pensionasset_pension'),
    ]

    operations = [
        migrations.AddField(
            model_name='pensionasset',
            name='pension',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pension_asset', to='pensionapp.pension'),
            preserve_default=False,
        ),
    ]
