# Generated by Django 4.0 on 2021-12-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pensionapp', '0004_pensionassettransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='pension',
            name='total_cash_amount',
            field=models.FloatField(default=0),
        ),
    ]
