# Generated by Django 4.0 on 2021-12-27 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pensionapp', '0005_pension_total_cash_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='pensionasset',
            name='total_dividend_amount',
            field=models.FloatField(default=0),
        ),
    ]
