# Generated by Django 4.0 on 2021-12-28 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0001_initial'),
        ('pensionapp', '0006_pensionasset_total_dividend_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='pension',
            name='portfolio',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='pension', to='portfolioapp.portfolio'),
            preserve_default=False,
        ),
    ]
