# Generated by Django 4.0 on 2021-12-28 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pensionapp', '0007_pension_portfolio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pension',
            name='dashboard',
        ),
    ]
