# Generated by Django 4.0 on 2021-12-21 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('dashboardapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_value', models.FloatField(default=0)),
                ('capital_gain', models.FloatField(default=0)),
                ('rate_of_return', models.FloatField(default=0)),
                ('capital_gain_foreign_exchange_adjusted', models.FloatField(default=0)),
                ('rate_of_return_foreign_exchange_adjusted', models.FloatField(default=0)),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('last_update_date', models.DateTimeField(auto_now_add=True)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to='dashboardapp.dashboard')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to='auth.user')),
            ],
        ),
    ]
