# Generated by Django 4.0 on 2022-01-06 08:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import guardianapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('guardianapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuardianTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('BUY', '매수'), ('SELL', '매도'), ('DIVIDEND', '배당금'), ('SPLIT', '액면분할')], max_length=20)),
                ('quantity', guardianapp.models.MinValueFloat()),
                ('price', guardianapp.models.MinValueFloat(default=0)),
                ('transaction_fee', models.FloatField(default=0)),
                ('transaction_tax', models.FloatField(default=0)),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.CharField(default=' - ', max_length=40, null=True)),
                ('split_cnt', models.IntegerField(default=0)),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('last_update_date', models.DateTimeField(auto_now_add=True)),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='guardianapp.guardian')),
            ],
        ),
    ]
