# Generated by Django 4.0 on 2022-01-12 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hozylabapp', '0002_temptransaction_applied_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='temptransaction',
            name='applied_date',
            field=models.DateTimeField(null=True),
        ),
    ]
